### ISSUE TITLE
'preserveComments': 'some' option fails with error

### ISSUE THREAD

**Issue by Dragonrun1** [hustxiaoc/gulp-minify#2]
When I try using the 'some' setting with gulp-minify I get an error and it fails. Here's is a copy of the error output I get:

``` log
D:\repos\local\incident_report\node_modules\promised-io\promise.js:242
						throw error;
						^

TypeError: Cannot set property 'comments' of undefined
    at Transform.minify [as _transform] (D:\repos\local\incident_report\node_modules\gulp-minify\index.js:88:28)
    at Transform._read (D:\repos\local\incident_report\node_modules\gulp-minify\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (D:\repos\local\incident_report\node_modules\gulp-minify\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (D:\repos\local\incident_report\node_modules\gulp-minify\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (D:\repos\local\incident_report\node_modules\gulp-minify\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Transform.Writable.write (D:\repos\local\incident_report\node_modules\gulp-minify\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (D:\repos\local\incident_report\node_modules\gulp-modernizr\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (D:\repos\local\incident_report\node_modules\gulp-modernizr\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at Transform.pipeOnReadable (D:\repos\local\incident_report\node_modules\gulp-modernizr\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at Transform.emit (events.js:166:7)
```
Here's  the related gulp task I'm using it in:

``` js
var gulp   = require('gulp');
var minify = require('gulp-minify');
var modernizr = require('gulp-modernizr');
var newer  = require('gulp-newer');
gulp.task('update:srcModernizr', function ()
{
    var moduleFiles    = 'node_modules/modernizr/src/**/*.js';
    var outputDir      = 'src/js/vendor/';
    var outFileName    = 'modernizr.js';
    var resultFileName = outputDir + outFileName;
    gulp.src(moduleFiles)
        .pipe(newer(resultFileName))
        .pipe(modernizr(outFileName))
        .pipe(minify({ 'preserveComments': 'some' }))
        .pipe(gulp.dest(outputDir));
});
```

After some more testing it seems to also fail for 'all'.
~~With a little more research I think I've figured out what the problems are. Instead of `options.output.comments = ...` it should be `options.comments = ...`~~

**Comment by ipanardian** [comment]
I have same issue

**Comment by hustxiaoc** [comment]
@Dragonrun1  @ipanardian sorry guys, issue has been solved!   
gulp-minify@0.0.9
