### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by francisrod01** [hustxiaoc/gulp-minify#28]
I need to deploy an application with gulpfile on production but one error persist and I don't understand your logs:

`$ gulp clean-build-app-prod && npm start`

error output below:

```
[04:58:40] Using gulpfile ~/projects/website/gulpfile.js
[04:58:40] Starting 'clean-prod'...
[04:58:40] Finished 'clean-prod' after 6.01 ms
[04:58:40] Starting 'clean-build-app-prod'...
[04:58:41] gulp-debug: app/app.js
[04:58:41] gulp-debug: app/appRoutes.js
[04:58:41] gulp-debug: app/js/controllers/MainCtrl.js
[04:58:41] gulp-debug: app/js/controllers/NavbarCtrl.js
[04:58:41] gulp-debug: app/js/controllers/PanelCtrl.js
[04:58:41] gulp-debug: app/js/controllers/UserCtrl.js
[04:58:41] gulp-debug: app/js/services/Page.js
[04:58:41] gulp-debug: app/js/services/SessionSrv.js
[04:58:41] gulp-debug: app/js/services/UserService.js
[04:58:41] gulp-debug: app/js/services/sessionInterceptor.js
[04:58:41] gulp-debug: 10 items
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Transform.minify [as _transform] (/home/paneladm/projects/website/node_modules/gulp-minify/index.js:127:33)
    at Transform._read (/home/paneladm/projects/website/node_modules/gulp-minify/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/paneladm/projects/website/node_modules/gulp-minify/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/paneladm/projects/website/node_modules/gulp-minify/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/paneladm/projects/website/node_modules/gulp-minify/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/paneladm/projects/website/node_modules/gulp-minify/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform.ondata (/home/paneladm/projects/website/node_modules/readable-stream/lib/_stream_readable.js:541:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
```

**Comment by simpleigh** [comment]
The error is raised on the following line (https://github.com/hustxiaoc/gulp-minify/blob/1.0.0/index.js#L127):

```javascript
min_file.sourceMap = JSON.parse(mangled.map);
```

It occurs because `mangled.map` is `undefined`, which isn't valid JSON (hence the "Unexpected token u" error when parsing the string `"undefined"`).

Version 2 of `uglify-js` outputs a map (https://github.com/mishoo/UglifyJS2/blob/v2.8.28/tools/node.js#L176-L179):

```javascript
return {
    code : stream + "",
    map  : source_map
};
```

... but since version 3, `uglify-js` and `uglify-es` don't do this unless the `sourceMap` option is passed (https://github.com/mishoo/UglifyJS2/blob/harmony/lib/minify.js#L149-L150):

```javascript
if (options.sourceMap) {
    result.map = options.output.source_map.toString();
    // ...
}
```

Unfortunately I don't think this happens - `uglifyOptions` are defined as follows before they're used (https://github.com/hustxiaoc/gulp-minify/blob/1.0.0/index.js#L112-L119):

```javascript
var uglifyOptions = {
    mangle   : options.mangle   !== undefined ? options.mangle : true,
    output   : options.output   !== undefined ? options.output : null,
    compress : options.compress !== undefined ? options.compress : {}
};
```

There's quite a lot of code (https://github.com/hustxiaoc/gulp-minify/blob/1.0.0/index.js#L89-L105) that modifies an `options` object, but the `uglifyOptions` object is the one that's passed to the `minify()` method. I suspect quite a lot of this code should instead be modifying `uglifyOptions` because otherwise I think it's redundant!

**Comment by simpleigh** [comment]
This commit is the problem (not surprisingly, since it's the only one between v0.0.15 and v1.0.0!): https://github.com/hustxiaoc/gulp-minify/commit/73646f86af1aa849d307775133d505f2453933b3.

This creates the `uglifyOptions` object and uses this in the call to `minify()`, therefore ignoring the `options` object so painstakingly created above.
